[package]
name = "pcs"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
parallel.workspace = true
primitives.workspace = true
fiat_shamir.workspace = true
serde.workspace = true
num-bigint.workspace = true
zk_alloc.workspace = true
tracing.workspace = true

[dev-dependencies]
primitives = { workspace = true, features = ["test-util"] }
bincode.workspace = true
